@startuml

header PE-JS

title
PE-JS
Data Flow Diagram - version 0.1.0
end title


autonumber

participant "PE-JS-Verifier" as PE2 order 0 #ORANGE
participant "Verifier" as V order 1 #ORANGE
participant "Alice" as A order 2 #PINK
participant "Wallet" as W order 3 #YELLOW
participant "PE-JS" as PE order 4 #YELLOW

V -> W: PresentationDefinition
W -> A: Notification
A -> W: Accepts PresentationDefinition
W -> PE: evaluate(presentationDefinition, allAvailableCredentials[])
PE -> W: evaluation results
W -> A: from the credentials that you've selected, \na combination of these are acceptable
A -> W: selects a combination of credentials
W -> PE: selectFrom(2ndSetOfCredentials[])
PE -> W: selectFrom response
W -> PE: submissionFrom(selectableCredentials)
PE -> W: submissionFrom response

W -> PE: createPresentation(selectFromResult)
PE -> W: get an actual Presentation object
W -> W: signPresentation(presentation)

W -> V: VerifiablePresentation

V -> PE2: evaluate(VerifiableCredential)
PE2 -> V: evaluation result
V -> W: Pass/Fail response
W -> A: Pass/Fail notification
@enduml